name: Deploy the archive from Repository.
on:
  push:
    tags:
      - stable
jobs:
  deploy-arhive:
    runs-on: ubuntu-latest
    steps:
      - name: Delete latest release
        uses: ame-yu/action-delete-latest-release@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          lfs: true
          clean: true
          fetch-depth: 1
          submodules: true
      - name: Archive the repository
        run: ./.ci/package.sh
        shell: bash
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.date.outputs.date }} - ${{ github.ref }}
          body:
          draft: false
          prerelease: false
      - name: Upload the archive to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deploy/JRTrainPack.zip
          asset_name: ${{ steps.date.outputs.date }}_JRTrainPack.zip
          asset_content_type: application/zip