name: Deploy the archive from Repository.
on:
  push:
    branches:
      - master
      - feature/github-actions
jobs:
  deploy-arhive:
    runs-on: ubuntu-latest
    steps:
      - name: Archive the repository
        run: sh ./.ci/package.sh
        shell: bash
      