name: Deploy the archive from Repository.
on: [push]
  branches: 
    - master
    - feature/github-actions
jobs: 
  deploy-arhive:
    steps:
      - name: Archive the repository
        run: echo "./ci/package.sh"
        shell: bash
      